### PR TITLE
fix techGay/v9porn issue#103 again

### PR DESCRIPTION
**Pull request by Cabchinoe**
fix techGay/v9porn issue#103 again

### CODE REVIEW

**Comment by sygsyg1982** [comment]
nice

**Comment by techGay** [comment]
把readme忽略重新提交一下吧

**Comment by Cabchinoe** [comment]
> 把readme忽略重新提交一下吧，github的merge怎么操作忽略？

好问题.....
https://stackoverflow.com/questions/15232000/git-ignore-files-during-merge 我只找到这个

- add  .gitattributes
- README.md merge=ours
- git config --global merge.ours.driver true

**Comment by zehuangchen** [comment]
thanks

**Pull request merged**
